name: Build and Deploy to Vercel

# When should this workflow run?
on:
  push:
    branches:
      - main

# Environment variables
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your project
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: bun install

      # Step 4: Run ESLint
      - name: Run Lint
        run: bun run lint

      # Step 5: Build the project
      - name: Build Project
        run: bun run build

      # Step 6: Install Vercel CLI
      - name: Install Vercel CLI
        run: bun add -g vercel

      # Step 7: Download Vercel project settings
      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      # Step 8: Build using Vercel
      - name: Build for Vercel
        run: vercel build --prod --token=$VERCEL_TOKEN

      # Step 9: Deploy
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN